import pandas as pd
import json
from sqlalchemy import text
from sklearn.metrics import classification_report
from sklearn.preprocessing import MultiLabelBinarizer
from src.database.connection import get_engine

# --- FINAL TAXONOMIES ---
ART_STYLE_KEYS = [
    "minimalist", "maximalist", "traditional_watercolor", 
    "crisp_digital_portrait", "cinematic", "handcrafted_diorama", 
    "surrealist", "standard_generic",
    "pop_art", "comic_book_illustration"
]

AESTHETIC_KEYS = [
    "kinetic", "chaotic", "modern", "whimsical", "legendary", "neutral"
]

def evaluate_taxonomy(df, keys, machine_col, title):
    y_true = []
    y_pred = []

    for _, row in df.iterrows():
        # 1. Parse Human Tags (From our secure JSONB column)
        human_tags_dict = row.get('tags', {})
        if isinstance(human_tags_dict, str):
            try: human_tags_dict = json.loads(human_tags_dict)
            except: human_tags_dict = {}
            
        human_labels = [k for k, v in human_tags_dict.items() if v == 1 and k in keys]
        y_true.append(human_labels)

        # 2. Parse Machine Tags (Generated by CLIP)
        machine_tags_list = row.get(machine_col, [])
        if isinstance(machine_tags_list, str):
            try: machine_tags_list = json.loads(machine_tags_list)
            except: machine_tags_list = []
            
        machine_labels = [k for k in machine_tags_list if k in keys]
        y_pred.append(machine_labels)

    # 3. Generate the Report Card
    mlb = MultiLabelBinarizer(classes=keys)
    true_matrix = mlb.fit_transform(y_true)
    pred_matrix = mlb.transform(y_pred)

    print("="*60)
    print(f"📊 {title.upper()}: CLIP MODEL vs HUMAN")
    print("="*60)
    print(classification_report(true_matrix, pred_matrix, target_names=keys, zero_division=0))
    print("\n")

def run_evaluation():
    engine = get_engine()
    
    # Fetch cards where humans have tagged AND the machine has made a prediction
    query = """
        SELECT card_id, tags, art_style, card_aesthetic 
        FROM tcg_cards 
        WHERE tags IS NOT NULL 
        AND art_style IS NOT NULL;
    """
    
    with engine.connect() as conn:
        df = pd.read_sql_query(text(query), conn)

    if df.empty:
        print("❌ No cards found with both human tags and machine predictions.")
        print("💡 TIP: Go to your Streamlit App -> Data Manager and run 'Run ML Enrichment' on your labeled sets first!")
        return

    print(f"\n🚀 Evaluating {len(df)} cards...")

    evaluate_taxonomy(df, ART_STYLE_KEYS, 'art_style', "Art Styles")
    evaluate_taxonomy(df, AESTHETIC_KEYS, 'card_aesthetic', "Card Aesthetics")

if __name__ == "__main__":
    run_evaluation()