# TCG Pokemon Sets displayed most recent first
sets:
  # Mega Evolution Expansion:
  "chaos-rising": "me4"
  "perfect-order": "me3"
  "ascended-heroes": "me2pt5"
  "phantasmal-flames": "me2"
  "mega-evolution": "me1"
  
  # Scarlet & Violet Expansion:
  "white-flare": "sv11w" 
  "black-bolt": "sv11b"
  "destined-rivals": "sv10"     # Keep this! It will resolve once the API updates.
  "journey-together": "sv9"
  "prismatic-evolutions": "sv8pt5"
  "surging-sparks": "sv8"
  "stellar-crown": "sv7"
  "shrouded-fable": "sv6pt5"
  "twilight-masquerade": "sv6"      # Great Sumi-e Ink and Watercolor examples
  "temporal-forces": "sv5"          
  "paldean-fates": "sv4pt5"         # Shiny Illustration Rares
  "paradox-rift": "sv4"             # Heavy on Surreal/Abstract & Maximalist
  "151": "sv3pt5"
  "obsidian-flames": "sv3"
  "paldea-evolved": "sv2"
  "sv-base": "sv1"

  # Sword & Shield Expansion:
  "crown-zenith-gg": "swsh12pt5gg"  # Galarian Gallery
  "crown-zenith": "swsh12pt5"
  "silver-tempest-tg": "swsh12tg"   # Trainer Gallery
  "silver-tempest": "swsh12"
  "lost-origin-tg": "swsh11tg"      # Trainer Gallery (Lots of Comic/Manga style)
  "lost-origin": "swsh11"
  "pokemon-go": "pgo"               # Summer 2022 Special Set
  "astral-radiance-tg": "swsh10tg"  # Trainer Gallery
  "astral-radiance": "swsh10"
  "brilliant-stars-tg": "swsh9tg"   # Trainer Gallery
  "brilliant-stars": "swsh9"
  "fusion-strike": "swsh8"
  "celebrations": "cel25"           # 25th Anniversary Special Set
  "evolving-skies": "swsh7"         # Famous for Eeveelution Alt Arts
  "chilling-reign": "swsh6"
  "battle-styles": "swsh5"          # Introduced SwSh Alternate Arts
  "shining-fates-sv": "swsh4pt5sv"  # Shiny Vault
  "shining-fates": "swsh4pt5"
  "vivid-voltage": "swsh4"
  "champions-path": "swsh3pt5"
  "darkness-ablaze": "swsh3"
  "rebel-clash": "swsh2"
  "swsh-base": "swsh1"


  # --- THE ASAKO ITO VINTAGE/MODERN ERA ---

  "cosmic-eclipse": "sm12"
  "unified-minds": "sm11"
  "unbroken-bonds": "sm10"
  "team-up": "sm9"
  "lost-thunder": "sm8"
  "celestial-storm": "sm7"
  "ultra-prism": "sm5"
  "sun-moon-base": "sm1"